SECRET_KEY='dev'
SESSION_COOKIE_SECURE=False
SESSION_COOKIE_HTTPONLY=True
SESSION_COOKIE_SAMESITE='Lax'
PREFERRED_URL_SCHEME='https'

CORS_HEADERS='Content-Type'

ABBREVIATIONS="https://docs.google.com/spreadsheets/d/e/2PACX-1vT-oEuvw0TTCyCl4bCBvhPXfACHx_tcGQO7nkA4_NOPKotRD6VRX2UDVQC4VyAFyy2zQwXs8A23eV24/pub?gid=0&single=true&output=csv"
